server:
  port: ${PORT:8080}

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://database-bf-hr-onboarding-system.cd00kukwmzu7.us-east-2.rds.amazonaws.com:3306/auth_service?useSSL=true&requireSSL=true&serverTimezone=UTC
    username: admin
    password: fBnqBRALQv.B4MV!e~ABfeBI|PAC
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  jwt:
    # defaults only; overridden by env vars
    secret: "1h5zRAoWTh//lgIZ0nTcwymBDHkyK8tmgUHZDECjQzNZDMfwl1tmPacaalzkFY/6+dqy9sIjcxr2YeTcGyG/Cw=="

  invite:
#    secret: ${INVITE_SECRET:dev-invite-secret-change-me-aaaaaaaaaaaaaaaa}
    secret: "WMjcUhiQ08AEvqF44+0K4XcAhAVpCyXK6Xt8Q9NfkCW/R2GyR3ix1f372/4UMeHzn7XhJ8lqRuFkjNfJrcEuRw=="
    default-hours: 3
  email:
    base-url: ${EMAIL_SERVICE_URL:http://localhost:8081}

    invite:
      registration-url-base: http://localhost:8080/auth/register











#server:
#  port: ${PORT:8080}
#
#
#  spring:
#    application:
#      name: auth-server
#
#    datasource:
#      # RDS endpoint your TL gave you (keep as-is)
#      url: jdbc:mysql://database-bf-hr-onboarding-system.cd00kukwmzu7.us-east-2.rds.amazonaws.com:3306/auth_service?useSSL=true&requireSSL=true&serverTimezone=UTC
#      # Use ONLY environment variables (no hardcoded secrets)
#      username: ${DB_USERNAME}
#      password: ${DB_PASSWORD}
#
#    jpa:
#      hibernate:
#        ddl-auto: none
#      show-sql: false
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL8Dialect
#
#  # Do NOT hardcode active profile. Set SPRING_PROFILES_ACTIVE=prod in env.
#  management:
#    endpoints:
#      web:
#        exposure:
#          include: health,info
#
#  app:
#    jwt:
#      # HMAC key (>=32 bytes). Provide via env.
#      secret: ${JWT_SECRET}
#      expiration-minutes: ${JWT_EXP_MINUTES:60}
#    invite:
#      # Secret used to sign invite tokens (also >=32 bytes)
#      secret: ${INVITE_SECRET}
#      default-hours: ${INVITE_DEFAULT_HOURS:3}
#    email:
#      base-url: ${EMAIL_SERVICE_URL:http://localhost:8081}

#spring:
#  application:
#    name: auth-server
#  datasource:
#    # 1) JDBC URL to your DB (RDS in your case)
#    # Replace the host with your team's RDS endpoint.
#    url: jdbc:mysql://database-bf-hr-onboarding-system.cd00kukwmzu7.us-east-2.rds.amazonaws.com:3306/auth_service?useSSL=true&requireSSL=true&serverTimezone=UTC
#    # 2) Username/password to log into MySQL
#    # Prefer environment variables; the value after the colon is a local default.
#    username: ${DB_USERNAME:auth_app}
#    password: ${DB_PASSWORD:Strong!Passw0rd}
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  profiles:
#    active: dev
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#
#app:
#  jwt:
#    secret: ${JWT_SECRET:dev-secret-change-me-please-32-bytes-minimum-aaaaaaaa}
#    expiration-minutes: 60
#  invite:
#    secret: ${INVITE_SECRET:dev-invite-secret-change-me-aaaaaaaaaaaaaaaa}
#    default-hours: 3
#  email:
#    base-url: ${EMAIL_SERVICE_URL:http://localhost:8081}